version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ${BENCHMARK_DIR}:/data
    #command: >
    #  bash -c "
    #  "

  frontend:
    build: ./frontend
    env_file:
      - .env
      - ./frontend/.env
    ports:
      - "${FRONTEND_PORT}:80"